# use container-based Ubuntu Trusty
dist: bionic
sudo: true

language: python
python:
  - "3.6.8"

services:
  - docker

install:
  - pip install pipenv
  - pipenv install --system --dev
script:
  - flake8
